In [1]:
import nltk
tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')

with open('/Users/maxwelllee54/GitHubs/Rapid_Assessment_Tools/SharedFiles/Fordham/RIA Bhutan/Docs Reviewed/Eleventh-Five-Year-Plan_Vol-1.txt') as f:
    data = f.read()
    text_list = tokenizer.tokenize(data)

In [2]:
import pandas as pd

SDG = pd.read_excel('/Users/maxwelllee54/GitHubs/Rapid_Assessment_Tools/SDG goals-v.2.xlsx').dropna()

In [4]:
SDG.head()

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>SDG Goal</th>
      <th>Goal name</th>
      <th>Goal Content</th>
      <th>SDG sub Goal</th>
      <th>SDG sub Goal content</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>Poverty</td>
      <td>Goal 1. End poverty in all its forms everywhere</td>
      <td>1.1</td>
      <td>1.1 By 2030, eradicate extreme poverty for all...</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>Poverty</td>
      <td>Goal 1. End poverty in all its forms everywhere</td>
      <td>1.2</td>
      <td>1.2 By 2030, reduce at least by half the propo...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1</td>
      <td>Poverty</td>
      <td>Goal 1. End poverty in all its forms everywhere</td>
      <td>1.3</td>
      <td>1.3 Implement nationally appropriate social pr...</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1</td>
      <td>Poverty</td>
      <td>Goal 1. End poverty in all its forms everywhere</td>
      <td>1.4</td>
      <td>1.4 By 2030, ensure that all men and women, in...</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1</td>
      <td>Poverty</td>
      <td>Goal 1. End poverty in all its forms everywhere</td>
      <td>1.5</td>
      <td>1.5 By 2030, build the resilience of the poor ...</td>
    </tr>
  </tbody>
</table>
</div>

In [19]:
X = SDG.loc[:,'SDG sub Goal content']
y = SDG.loc[:,'SDG Goal']

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(ngram_range=(1,2))

In [21]:
vect.fit(X)
X_train_dtm = vect.transform(X)

In [22]:
X_train_dtm

<159x3800 sparse matrix of type '<class 'numpy.int64'>'
	with 7910 stored elements in Compressed Sparse Row format>

In [23]:
X_test = ['Strategic Human Settlements developed for regionally balanced development and improved quality of life and socioeconomic status of both urban and rural residents']

In [24]:
X_test_dtm = vect.transform(X_test)
X_test_dtm

<1x3800 sparse matrix of type '<class 'numpy.int64'>'
	with 18 stored elements in Compressed Sparse Row format>

In [25]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [26]:
nb.fit(X_train_dtm, y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [28]:
y_pred_class = nb.predict(X_test_dtm)
y_pred_class

array([17])

In [29]:
from sklearn.multiclass import OneVsOneClassifier, OneVsRestClassifier
from sklearn.svm import LinearSVC

OneVsRestClassifier(LinearSVC(random_state=0)).fit(X_train_dtm, y).predict(X_test_dtm)

array([4])

In [30]:
OneVsOneClassifier(LinearSVC(random_state=0)).fit(X_train_dtm, y).predict(X_test_dtm)

array([8])

Wrong Prediction. Sad