In [123]:
import nltk
tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')

with open('/Users/maxwelllee54/GitHubs/Rapid_Assessment_Tools/SharedFiles/Fordham/RIA Bhutan/Docs Reviewed/Eleventh-Five-Year-Plan_Vol-1.txt') as f:
    data = f.read()
    text_list = tokenizer.tokenize(data)

In [124]:
sentences = []
for text in text_list:
    token = nltk.word_tokenize(text)
    sentence = ' '.join(token)
    sentences.append(sentence)

In [125]:
import pandas as pd

SDG = pd.read_excel('/Users/maxwelllee54/GitHubs/Rapid_Assessment_Tools/SDG goals-v.2.xlsx').dropna()

In [126]:
SDG.head()

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>SDG Goal</th>
      <th>Goal name</th>
      <th>Goal Content</th>
      <th>SDG sub Goal</th>
      <th>SDG sub Goal content</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>Poverty</td>
      <td>Goal 1. End poverty in all its forms everywhere</td>
      <td>1.1</td>
      <td>1.1 By 2030, eradicate extreme poverty for all...</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>Poverty</td>
      <td>Goal 1. End poverty in all its forms everywhere</td>
      <td>1.2</td>
      <td>1.2 By 2030, reduce at least by half the propo...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1</td>
      <td>Poverty</td>
      <td>Goal 1. End poverty in all its forms everywhere</td>
      <td>1.3</td>
      <td>1.3 Implement nationally appropriate social pr...</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1</td>
      <td>Poverty</td>
      <td>Goal 1. End poverty in all its forms everywhere</td>
      <td>1.4</td>
      <td>1.4 By 2030, ensure that all men and women, in...</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1</td>
      <td>Poverty</td>
      <td>Goal 1. End poverty in all its forms everywhere</td>
      <td>1.5</td>
      <td>1.5 By 2030, build the resilience of the poor ...</td>
    </tr>
  </tbody>
</table>
</div>

In [127]:
X = SDG.loc[:,'SDG sub Goal content']
y = SDG.loc[:,'SDG Goal']

In [128]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(ngram_range=(1,2))

In [129]:
vect.fit(X)
X_train_dtm = vect.transform(X)

In [130]:
X_train_dtm

<159x3800 sparse matrix of type '<class 'numpy.int64'>'
	with 7910 stored elements in Compressed Sparse Row format>

In [131]:
X_test = ['Strategic Human Settlements developed for regionally balanced development and improved quality of life and socioeconomic status of both urban and rural residents']

In [132]:
X_test_dtm = vect.transform(X_test)
X_test_dtm

<1x3800 sparse matrix of type '<class 'numpy.int64'>'
	with 18 stored elements in Compressed Sparse Row format>

In [133]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [134]:
nb.fit(X_train_dtm, y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [135]:
y_pred_class = nb.predict(X_test_dtm)
y_pred_class

array([17])

In [136]:
from sklearn.multiclass import OneVsOneClassifier, OneVsRestClassifier
from sklearn.svm import LinearSVC

OneVsRestClassifier(LinearSVC(random_state=0)).fit(X_train_dtm, y).predict(X_test_dtm)

array([4])

In [137]:
OneVsOneClassifier(LinearSVC(random_state=0)).fit(X_train_dtm, y).predict(X_test_dtm)

array([8])

Wrong Prediction. Sad

In [175]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(ngram_range=(1,1))

In [176]:
df = X 
#df.loc['test'] = sentences[500]
df.loc['test'] = '''
Generate additional employment opportunities and increase mean annual rural household cash income
'''

In [177]:
tfidf = vectorizer.fit_transform(df)        
pairwise_similarity = tfidf * tfidf.T

In [178]:
pairwise_similarity.A[-1, :-1]

array([ 0.        ,  0.00387488,  0.01293758,  0.01406606,  0.02100066,
        0.00642935,  0.00707074,  0.01098371,  0.01179896,  0.09642261,
        0.0364039 ,  0.02207164,  0.09530934,  0.00812365,  0.00568207,
        0.        ,  0.00421832,  0.00955197,  0.01158166,  0.00814403,
        0.00503366,  0.01412685,  0.00994551,  0.01749742,  0.        ,
        0.01044098,  0.04561957,  0.00942152,  0.01553111,  0.00649839,
        0.01464434,  0.09149643,  0.01052563,  0.01385927,  0.01210915,
        0.01512406,  0.01343147,  0.04047585,  0.00615215,  0.01643359,
        0.00871725,  0.08202737,  0.08490429,  0.01399663,  0.00940705,
        0.00500798,  0.01698373,  0.0123829 ,  0.01839397,  0.01270243,
        0.03632456,  0.        ,  0.0090556 ,  0.01316335,  0.01147979,
        0.00648494,  0.04644604,  0.        ,  0.01158089,  0.00971235,
        0.00322415,  0.00749592,  0.0127463 ,  0.00892967,  0.05884364,
        0.07072499,  0.01390266,  0.05656245,  0.01386392,  0.00