In [123]:
import nltk
tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')

with open('/Users/maxwelllee54/GitHubs/Rapid_Assessment_Tools/SharedFiles/Fordham/RIA Bhutan/Docs Reviewed/Eleventh-Five-Year-Plan_Vol-1.txt') as f:
    data = f.read()
    text_list = tokenizer.tokenize(data)

In [124]:
sentences = []
for text in text_list:
    token = nltk.word_tokenize(text)
    sentence = ' '.join(token)
    sentences.append(sentence)

In [125]:
import pandas as pd

SDG = pd.read_excel('/Users/maxwelllee54/GitHubs/Rapid_Assessment_Tools/SDG goals-v.2.xlsx').dropna()

In [126]:
SDG.head()

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>SDG Goal</th>
      <th>Goal name</th>
      <th>Goal Content</th>
      <th>SDG sub Goal</th>
      <th>SDG sub Goal content</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>Poverty</td>
      <td>Goal 1. End poverty in all its forms everywhere</td>
      <td>1.1</td>
      <td>1.1 By 2030, eradicate extreme poverty for all...</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>Poverty</td>
      <td>Goal 1. End poverty in all its forms everywhere</td>
      <td>1.2</td>
      <td>1.2 By 2030, reduce at least by half the propo...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1</td>
      <td>Poverty</td>
      <td>Goal 1. End poverty in all its forms everywhere</td>
      <td>1.3</td>
      <td>1.3 Implement nationally appropriate social pr...</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1</td>
      <td>Poverty</td>
      <td>Goal 1. End poverty in all its forms everywhere</td>
      <td>1.4</td>
      <td>1.4 By 2030, ensure that all men and women, in...</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1</td>
      <td>Poverty</td>
      <td>Goal 1. End poverty in all its forms everywhere</td>
      <td>1.5</td>
      <td>1.5 By 2030, build the resilience of the poor ...</td>
    </tr>
  </tbody>
</table>
</div>

In [127]:
X = SDG.loc[:,'SDG sub Goal content']
y = SDG.loc[:,'SDG Goal']

In [128]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(ngram_range=(1,2))

In [129]:
vect.fit(X)
X_train_dtm = vect.transform(X)

In [130]:
X_train_dtm

<159x3800 sparse matrix of type '<class 'numpy.int64'>'
	with 7910 stored elements in Compressed Sparse Row format>

In [131]:
X_test = ['Strategic Human Settlements developed for regionally balanced development and improved quality of life and socioeconomic status of both urban and rural residents']

In [132]:
X_test_dtm = vect.transform(X_test)
X_test_dtm

<1x3800 sparse matrix of type '<class 'numpy.int64'>'
	with 18 stored elements in Compressed Sparse Row format>

In [133]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [134]:
nb.fit(X_train_dtm, y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [135]:
y_pred_class = nb.predict(X_test_dtm)
y_pred_class

array([17])

In [136]:
from sklearn.multiclass import OneVsOneClassifier, OneVsRestClassifier
from sklearn.svm import LinearSVC

OneVsRestClassifier(LinearSVC(random_state=0)).fit(X_train_dtm, y).predict(X_test_dtm)

array([4])

In [137]:
OneVsOneClassifier(LinearSVC(random_state=0)).fit(X_train_dtm, y).predict(X_test_dtm)

array([8])

Wrong Prediction. Sad

In [138]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(ngram_range=(1,3))

In [168]:
df = X 
#df.loc['test'] = sentences[500]
df.loc['test'] = '''
Generate additional employment opportunities and increase mean annual rural household cash income
'''

In [169]:
tfidf = vectorizer.fit_transform(df)        
pairwise_similarity = tfidf * tfidf.T

In [170]:
pairwise_similarity.A[-1, :-1]

array([ 0.        ,  0.00096032,  0.00319892,  0.00367119,  0.00529679,
        0.0016061 ,  0.00186085,  0.00274588,  0.00309695,  0.02489899,
        0.01006121,  0.00607656,  0.02541271,  0.0022802 ,  0.00160929,
        0.        ,  0.00118773,  0.00285221,  0.00309263,  0.00231906,
        0.00136054,  0.00366681,  0.00271868,  0.0045788 ,  0.        ,
        0.00302703,  0.01197521,  0.00223247,  0.00411016,  0.00181251,
        0.0034974 ,  0.02469952,  0.00261932,  0.00355405,  0.00323484,
        0.00399583,  0.00362279,  0.01039315,  0.00165616,  0.00413268,
        0.00244969,  0.02155762,  0.02107754,  0.0037299 ,  0.00252316,
        0.00126622,  0.0041598 ,  0.0028794 ,  0.00460403,  0.00339704,
        0.0100489 ,  0.        ,  0.0024608 ,  0.00352729,  0.00280227,
        0.00162103,  0.01216544,  0.        ,  0.00369228,  0.0024967 ,
        0.00094562,  0.0020044 ,  0.00330869,  0.00230016,  0.0158546 ,
        0.01799287,  0.0040394 ,  0.01541724,  0.00358059,  0.00